# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-31 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('user_town', models.CharField(max_length=100, verbose_name='Город')),
                ('user_text', models.TextField(default='', verbose_name='Текст отзыва')),
                ('answer_text', models.TextField(default='', verbose_name='Текст ответа на отзыв')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата написания')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Подтверждено')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
