# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-31 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('user_mail', models.CharField(max_length=100, verbose_name='Почта')),
                ('user_phone', models.CharField(max_length=100, verbose_name='Телефон')),
                ('user_insta', models.CharField(max_length=100, verbose_name='Инстаграм')),
                ('user_skype', models.CharField(max_length=100, verbose_name='Скайп')),
                ('user_periskop', models.CharField(max_length=100, verbose_name='Перископ')),
                ('user_vk', models.CharField(max_length=100, verbose_name='ВК')),
                ('user_fb', models.CharField(max_length=100, verbose_name='FB')),
                ('user_tw', models.CharField(max_length=100, verbose_name='Twitter')),
                ('user_copyright', models.TextField(default='', verbose_name='Копирайт')),
                ('about_text', models.TextField(default='', verbose_name='Общее описание обо мне')),
                ('about_short_text', models.TextField(default='', verbose_name='Короткое описание обо мне')),
            ],
            options={
                'verbose_name': 'Обо мне',
                'verbose_name_plural': 'Обо мне',
            },
        ),
    ]
