# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-31 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160831_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_year', models.DateField(default=django.utils.timezone.now, verbose_name='Дата события')),
                ('story_text', models.CharField(max_length=100, verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'События',
                'verbose_name': 'События',
            },
        ),
    ]
