# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-31 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20160831_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_image',
            field=models.ImageField(null=True, upload_to='media', verbose_name='Изображение'),
        ),
    ]
