# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-31 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_news_news_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutme',
            name='id',
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='user_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Имя'),
        ),
    ]
