# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-31 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20160831_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='user_mail',
            field=models.EmailField(max_length=100, verbose_name='Почта'),
        ),
    ]
