# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-05 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20160831_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('user_email', models.EmailField(max_length=100, verbose_name='Email')),
                ('user_text', models.TextField(default='', max_length=500, verbose_name='Текст')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата написания')),
            ],
            options={
                'verbose_name': 'Письмо',
                'verbose_name_plural': 'Письма',
            },
        ),
        migrations.AlterField(
            model_name='review',
            name='user_text',
            field=models.TextField(default='', max_length=500, verbose_name='Текст отзыва'),
        ),
    ]
