# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-05 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20160905_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='to_main',
            field=models.BooleanField(default=False, verbose_name='на главную страницу'),
        ),
    ]
