# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_review_to_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutme',
            name='about_short_text',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='about_text',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='user_copyright',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='user_fb',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='user_insta',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='user_mail',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='user_periskop',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='user_phone',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='user_skype',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='user_tw',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='user_unique',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='user_vk',
        ),
        migrations.AddField(
            model_name='aboutme',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutme',
            name='user_data',
            field=models.CharField(choices=[(1, 'Name'), (2, 'Email'), (3, 'Phone'), (4, 'Instagram'), (5, 'Skype'), (6, 'Periskop'), (7, 'Vk'), (8, 'Fb'), (9, 'Copyright'), (10, 'Twitter'), (11, 'About me'), (12, 'About me short')], default='unique', max_length=1000, verbose_name='Select rules for customer segmentation'),
        ),
    ]
