# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20160906_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutme',
            name='id',
        ),
        migrations.AddField(
            model_name='aboutme',
            name='user_field',
            field=models.CharField(choices=[(1, 'Name'), (2, 'Email'), (3, 'Phone'), (4, 'Instagram'), (5, 'Skype'), (6, 'Periskop'), (7, 'Vk'), (8, 'Fb'), (9, 'Copyright'), (10, 'Twitter'), (11, 'About me'), (12, 'About me short')], default='Name', max_length=100, primary_key=True, serialize=False, verbose_name='Выберите раздел'),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='user_data',
            field=models.CharField(default='', max_length=1000, verbose_name='Данные'),
        ),
    ]
